{
    "appname": "Application unreachable 12/06/2021",
    "class": [
        "regular_node"
    ],
    "comments": [
        {
            "text": "",
            "tstp": 1634842751.8913453,
            "user_info": {
                "first_name": "Sarang",
                "last_name": "Dharmapurikar",
                "org": "DagKnows",
                "role": "Admin",
                "uname": "sarang@dagknows.com"
            }
        },
        {
            "text": "",
            "tstp": 1634842794.1531134,
            "user_info": {
                "first_name": "Sarang",
                "last_name": "Dharmapurikar",
                "org": "DagKnows",
                "role": "Admin",
                "uname": "sarang@dagknows.com"
            }
        }
    ],
    "conv_id": "zRQE-nHW8oULaLivmQXCyQ",
    "currsession": "5QUCa3rc0AmfSh7Q",
    "description": "<p><br></p>",
    "evidence": "cmd = 'ping -c 1 ' + dns_server\nop = _exe(None, cmd)\n_problem = True\nif '0% packet loss' in op:\n    _problem = False\n",
    "evidtype": "Script",
    "msg": "",
    "nodename": {
        "input_params": {
            "dns_server": "dns_server"
        },
        "node_func": "DNS server unreachable"
    },
    "nodetype": "Problem",
    "prevnodename": {
        "node_func": "DNS server unreachable"
    },
    "privacy_level": "internal",
    "related_convs": [
        [
            "zendesk__5",
            "Connectivity problems with the instances (Zendesk ticket: 5)"
        ],
        [
            "QTRKPvHmchKjkOx_m-RJ7w",
            "App not responding"
        ]
    ],
    "res": "<p><br></p>",
    "restype": "Description",
    "state": "approved",
    "tags": {
        "_dag": "Netflix,DNS,network_issues,Connectivity"
    },
    "node_id": "iEYyMs1c7ZoNEolP",
    "metadata": {
        "create_tstp": 1662428424.407293,
        "create_username": "info@dagknows.com"
    }
}